// Per-listing brochure copy, keyed by vessel slug. Consumed only by the
// print route at /listings/[slug]/brochure. Fleet cards do NOT import this.
// Hero image, name, year, make, length, location, price, badge come from the
// matching Vessel in fleet.ts (linked by slug); this file holds brochure-only copy.

export type SpecCell = { value: string; label: string; sub?: string };

export type BrochureContent = {
  slug: string;
  // Headline: renders as `${lead} <gold-italic>${emphasis}</gold-italic> ${tail}`
  tagline: { lead: string; emphasis: string; tail: string };
  specStrip: SpecCell[];        // up to 5 cells; powerboats may use fewer
  narrative: string[];          // body paragraphs, in order
  highlights: string[];         // 2-column bullet table, in order
  documentation?: { officialNo?: string; callSign?: string; note?: string };
  photoCredit?: string;         // place shown in "Photographed at <x> · Gray Yachts Media"
};

export const brochures: Record<string, BrochureContent> = {
  poulsbo: {
    slug: "poulsbo",
    tagline: {
      lead: "A",
      emphasis: "high-speed aluminum research platform",
      tail: "— jet driven, survey equipped, shallow-water capable.",
    },
    specStrip: [
      { value: "38' × 12'", label: "Length & Beam" },
      { value: "1,100hp", label: "Twin Gas Power" },
      { value: "40 kt", label: "Cruise Speed" },
      { value: "500 mi", label: "Range" },
      { value: "2,000 lb", label: "A-Frame Capacity" },
    ],
    narrative: [
      "R/V Poulsbo is a custom 38-foot welded-aluminum patrol and research vessel engineered for sampling, survey, and support work across Puget Sound. Her hull and propulsion package pair offshore strength with the shallow-water access demanded by nearshore field operations.",
      "Twin 550-horsepower gasoline engines drive waterjets for 1,100 total horsepower, a 40-knot cruise, and close-quarters control without exposed propellers. Five hundred gallons of fuel support an estimated 500-mile range, giving crews the speed and endurance to move between distant work sites in a single operating window.",
      "The stern working deck centers on a hydraulic A-frame and custom research winch rated for equipment deployments up to 2,000 pounds. The arrangement supports towed video and side-scan sonar, while dedicated bow and stern pole mounts are configured for multibeam and sub-bottom survey equipment. Three-phase power is available for vibracoring and ROV operations.",
      "Inside, a full cabin provides protected work space, a dinette, crew berths, an enclosed head, and a survey-ready main helm. Radar, VHF, chartplotter, survey sonar, and a Trimble 461 RTK GPS system are joined by inverter and solar systems that provide clean power for sensitive electronics. Offered at $300,000 and available for inspection by appointment.",
    ],
    highlights: [
      "Custom welded-aluminum patrol / research vessel",
      "Twin 550hp gasoline engines — 1,100hp total",
      "Waterjet propulsion — offshore & shallow-water capable",
      "40-knot cruise · estimated 500-mile range",
      "500-gallon gasoline capacity",
      "Hydraulic stern A-frame — 2,000 lb capacity",
      "Custom research winch",
      "Towed video & side-scan sonar deployment setup",
      "Bow & stern sonar pole mounts",
      "Multibeam & sub-bottom survey configured",
      "Three-phase power for vibracoring and ROVs",
      "Radar, VHF, chartplotter & Trimble 461 RTK GPS",
      "Inverter and solar clean-power system",
      "Crew berths, work space, heater & enclosed head",
    ],
    photoCredit: "Puget Sound, WA",
  },
  "playa-linda": {
    slug: "playa-linda",
    tagline: {
      lead: "A",
      emphasis: "capable center cockpit",
      tail: "cruiser — built for short-handed bluewater passages.",
    },
    specStrip: [
      { value: "42.5'", label: "Length" },
      { value: "1994", label: "Year Built" },
      { value: "Yanmar", label: "62hp Diesel" },
      { value: "14'", label: "Beam" },
      { value: "Sloop", label: "B&R Rig" },
    ],
    narrative: [
      "The Hunter Passage 42 is one of the most capable center cockpit cruisers ever produced — two private staterooms, two heads, a 14-foot beam, and a B&R masthead rig designed for short-handed sailing. This 1994 example, Playa Linda, has been actively cruised on Pacific Northwest waters and is ready for her next passage.",
      "Below, warm teak and holly soles run throughout with 6'6\" headroom. A spacious salon with an L-shaped settee and convertible dining opens to a fully equipped galley with refrigerator and stove. The forward stateroom carries a V-berth and private head with shower; the aft owner's cabin a queen berth with en-suite head, tub, and shower.",
      "On deck, a protected center cockpit under dodger and bimini keeps the crew comfortable, with all lines led aft, a roller-furling jib, and self-tailing winches for easy handling. Solar panels on the arch cut shore-power dependence, and a walk-through transom with swim platform makes boarding effortless. Service records available; sea trial welcome.",
    ],
    highlights: [
      "Two private staterooms, two heads",
      "Yanmar 4JH2TE, 62hp diesel — direct drive",
      "B&R masthead sloop — 949 sq ft sail area",
      "14' beam, wing keel, 4.9' draft",
      "Roller-furling jib, all lines led aft",
      "Self-tailing winches, dodger & bimini",
      "Solar array on stern arch",
      "Teak & holly soles, 6'6\" headroom",
      "Fully equipped galley — fridge & stove",
      "Aft owner's cabin — queen, en-suite tub & shower",
      "Walk-through transom, swim platform",
      "70 gal fuel · 150 gal water · ~900 engine hours",
    ],
    photoCredit: "the San Juan Islands, WA",
  },
  seawulff: {
    slug: "seawulff",
    tagline: {
      lead: "A",
      emphasis: "classic Pacific Northwest",
      tail: "wooden sail vessel — built to last, documented to prove it.",
    },
    specStrip: [
      { value: "34.5'", label: "Length" },
      { value: "1981", label: "Year Built" },
      { value: "Saab", label: "30hp Diesel" },
      { value: "4–6", label: "Sleeps" },
      { value: "Wood", label: "Construction" },
    ],
    narrative: [
      "Seawulff is a 1981 wood-hulled auxiliary sailboat built in Olympia, Washington and hailing from Port Townsend — one of the most storied wooden boat communities on the West Coast. Yellow Cedar, Port Orford Cedar, and Western Red Cedar planking over steam-bent White Oak frames. Teak-planked cabin tops. Bronze hardware throughout. This is a vessel built the old way, for the long run.",
      "She carries a full Dacron sail inventory — main, staysail, jib, and drifter — along with 1x19 stainless standing rigging and a double forestay. The Saab 2-cylinder diesel starts clean, with injector pump rebuilt and injectors checked. Two trunk cabins, V-berth forward, main salon with U-shaped settee, galley aft to port, and a dedicated aft cabin with counter workspace.",
      "Previously USCG-certified for passenger operation on Puget Sound — a level of inspection most private vessels never see. Clean documentation. Survey history on file. Ready for her next chapter.",
    ],
    highlights: [
      "Cedar & Teak construction throughout",
      "Saab 2-cyl diesel, 30hp — starts clean",
      "Full Dacron sail inventory included",
      "140 gal water capacity — dual S/steel tanks",
      "Dickinson diesel cabin heater",
      "Bronze fastenings & keel bolts w/ backing plates",
      "30A shore power, 4x 12V battery bank",
      "Electro Guard galvanic protection system",
      "VHF, depthfinder, binnacle compass",
      "8-person life raft, full USCG safety kit",
      "Stern arch w/ dedicated hydraulic winch",
      "Plow anchor + 160 ft chain rode",
    ],
    documentation: {
      officialNo: "634426",
      callSign: "WTS4768",
      note: "Certified for Puget Sound, Lakes, Bays & Sounds. Inspected and approved for up to 10 passengers under USCG Sector Puget Sound — a standard of documentation that sets this vessel apart from typical private listings.",
    },
    photoCredit: "Port Townsend, WA",
  },
  "dub-sea": {
    slug: "dub-sea",
    tagline: {
      lead: "The",
      emphasis: "flagship of the Cobalt line",
      tail: "— twin power, a deep-vee hull, and a proven Pacific Northwest track record.",
    },
    specStrip: [
      { value: "29'", label: "Length" },
      { value: "2016", label: "Year Built" },
      { value: "Twin", label: "MerCruiser 600hp" },
      { value: "9.5'", label: "Beam" },
      { value: "Deep Vee", label: "Fiberglass Hull" },
    ],
    narrative: [
      "The Cobalt 293 is the flagship of the legendary Cobalt line — a deep-vee fiberglass cruiser built with Hydrolam construction and a Kevlar-reinforced keel for confident performance in Pacific Northwest water. Dub Sea is maintained, turn-key, and comes trailer-ready.",
      "Twin MerCruiser 350 MAG MPI stern drives deliver 600 horsepower with 780 hours logged, moving the 29-foot hull with the ease Cobalt is known for. A roomy cuddy cabin offers weekend-ready shelter below, while the open cockpit seats a crowd for a day on the Sound.",
      "A tri-axle trailer is included, making haul-out, storage, and trailering to new water effortless. Cared for and ready to run — sea trial welcome.",
    ],
    highlights: [
      "Twin MerCruiser 350 MAG MPI — 600hp total",
      "780 hours logged",
      "Deep-vee fiberglass hull — Hydrolam construction",
      "Kevlar-reinforced keel",
      "29' LOA · 9.5' beam",
      "110 gallon fuel capacity",
      "Cuddy cabin — weekend-ready shelter",
      "Tri-axle trailer included",
      "Maintained, turn-key & trailer-ready",
      "Proven Pacific Northwest track record",
    ],
    photoCredit: "Seattle, WA",
  },
  "moby-dick": {
    slug: "moby-dick",
    tagline: {
      lead: "A",
      emphasis: "nearly-new weekend cruiser",
      tail: "— comfort, practicality, and style for day trips and overnights alike.",
    },
    specStrip: [
      { value: "23'", label: "Length" },
      { value: "2023", label: "Year Built" },
      { value: "Mercury", label: "175hp Outboard" },
      { value: "8", label: "Capacity" },
      { value: "Cuddy", label: "Weekender" },
    ],
    narrative: [
      "This 2023 Quicksilver 675 Weekend blends comfort, practicality, and style for new and experienced boaters alike. Lightly used and presented in excellent condition throughout, Moby Dick is the rare opportunity to step aboard a nearly-new cruiser without the wait.",
      "The layout is built for day cruising and overnight stays: a comfortable saloon converts to a berth with in-fill cushions, and an enclosed heads compartment houses a manual toilet. The galley is neatly equipped with a sink and tap, refrigerator, and ample storage for weekends away.",
      "The helm is well-appointed with a Simrad chartplotter, Lowrance VHF, Mercury engine dials, and a double USB charger, all paired with a comfortable bolster seat. A Webasto heating system, interior curtains, an opening roof hatch, and full surround canvas keep her comfortable in any weather, while the cockpit offers a table, cushioned seating, and rod holders for relaxed days on the water.",
    ],
    highlights: [
      "Mercury 175hp outboard — low hours",
      "Saloon converts to an overnight berth",
      "Enclosed heads with manual toilet",
      "Galley — sink, tap & refrigerator",
      "Simrad chartplotter & Lowrance VHF",
      "Webasto cabin heating system",
      "Opening roof hatch & full surround canvas",
      "Electric anchor windlass",
      "Cockpit table, cushioned seating & rod holders",
      "Fusion entertainment system w/ speakers",
      "Waste tank with pump-out",
      "Stainless railings, nav & exterior lighting",
    ],
    photoCredit: "Puget Sound, WA",
  },
  "yamaha-252se": {
    slug: "yamaha-252se",
    tagline: {
      lead: "A",
      emphasis: "turn-key Yamaha jet boat",
      tail: "— twin-engine performance and effortless day-boat versatility.",
    },
    specStrip: [
      { value: "25'", label: "Length" },
      { value: "2022", label: "Year Built" },
      { value: "Twin 1.8L", label: "Yamaha HO Jet" },
      { value: "8'6\"", label: "Beam" },
      { value: "12", label: "Capacity" },
    ],
    narrative: [
      "The Yamaha 252SE is the do-everything Pacific Northwest day boat — twin Yamaha 1.8-liter High Output jet engines deliver quick, confident performance with no outboard to clutter the swim platform. This 2022 example is presented in turn-key condition, ready for summer on the water.",
      "Jet propulsion means a shallow draft, easy beaching, and a wide-open swim platform with integrated sundeck and reboarding ladder — ideal for swimming, watersports, and rafting up. The helm centers on Yamaha's Connext touchscreen with cruise assist and No Wake Mode for low-speed control.",
      "Seating wraps the cockpit and bow for a full crew, with a filler cushion to convert the bow to a sun lounge. A premium audio system, bimini top, and ample stowage round out a boat built to make the most of short Northwest seasons.",
    ],
    highlights: [
      "Twin Yamaha 1.8L High Output jet engines",
      "Yamaha Connext touchscreen helm",
      "No Wake Mode & cruise assist",
      "Integrated swim platform with sundeck",
      "Reboarding ladder & transom shower",
      "Bow filler cushion — converts to sun lounge",
      "Premium audio system",
      "Bimini top & full canvas",
      "Shallow-draft jet propulsion",
      "Wraparound cockpit & bow seating",
    ],
    photoCredit: "Lake Washington, WA",
  },
  neverland: {
    slug: "neverland",
    tagline: {
      lead: "A",
      emphasis: "true pocket cruiser",
      tail: "— enclosed pilothouse, private cabin, and outboard simplicity in 24 feet.",
    },
    specStrip: [
      { value: "24'6\"", label: "Length" },
      { value: "8'4\"", label: "Beam" },
      { value: "Mercury", label: "Outboard" },
      { value: "1,200", label: "Engine Hours" },
      { value: "46 gal", label: "Fuel" },
    ],
    narrative: [
      "Neverland is a Bénéteau Antares 7 — the French builder's most successful pocket cruiser, and one of the very few boats under 25 feet that delivers a genuine enclosed pilothouse, a private cabin, and outboard simplicity in a single trailerable package. She runs a single Mercury outboard, carries Garmin electronics at the helm, and presents the way a boat does when it has lived under cover.",
      "The hardtop pilothouse is why this model earned its reputation on Northwest water. A sliding door and opening side glass turn the helm from a fully enclosed wheelhouse into an open-air cockpit in seconds — the difference between a boat you use three months a year and one you use nine. Inside, a solid wenge-toned table drops to convert the settee into a berth, with a second private cabin aft, tucked under the cockpit sole. White gelcoat, warm joinery, and Bénéteau fit and finish throughout.",
      "On deck, walkaround side decks run forward past stainless rails and a bow pulpit to a self-draining anchor locker. Aft, twin boarding platforms flank the outboard well with a folding swim ladder, making the water easy to get into and easier to get out of. Forty-six gallons of fuel give her honest range for the Sound and the San Juans, and because she trailers behind a properly rated tow vehicle, her cruising ground is not limited to her home port.",
      "Twelve hundred hours are logged on the Mercury and the boat is offered at $75,000 — in line with the national market for the model. Maintenance records, full spec sheet, and sea trial available on request.",
    ],
    highlights: [
      "Bénéteau Antares 7 — hardtop pocket cruiser",
      "Single Mercury outboard · 1,200 hours",
      "Enclosed pilothouse — sliding door & side glass",
      "Garmin chartplotter at the helm",
      "Convertible dinette — table drops to berth",
      "Private aft cabin beneath the cockpit",
      "24'6\" LOA · 8'4\" beam",
      "46 gallon fuel capacity",
      "Walkaround decks, bow pulpit & anchor locker",
      "Twin boarding platforms w/ folding swim ladder",
      "Covered moorage · stored indoors",
      "Trailerable — WA registered WN 4540 AU",
    ],
    photoCredit: "Seattle, WA",
  },
  "un-reel-2": {
    slug: "un-reel-2",
    tagline: {
      lead: "A",
      emphasis: "no-compromise Northwest",
      tail: "fishing boat — composite built, factory backed.",
    },
    specStrip: [
      { value: "24'6\"", label: "Length" },
      { value: "2023", label: "Year Built" },
      { value: "Mercury", label: "175XL Outboard" },
      { value: "1,505", label: "Engine Hours" },
      { value: "100 gal", label: "Fuel" },
    ],
    narrative: [
      "Un Reel 2 is a 2023 Defiance San Juan 220 — a Pacific Northwest fishing platform built the way Northwest boats ought to be. A fully composite hull with no wood coring anywhere, a 21-degree deep-vee that settles into a Sound chop, and a hardtop pilothouse you can genuinely fish from in February. One owner, maintained since new by a professional service department.",
      "The San Juan 220 refuses to choose between fishing and cruising. The pilothouse carries a proper helm, a convertible dinette that drops down into a berth, and enough enclosed, heated-in space for a family to wait out weather that would end the day on an open boat. Step aft through the side door and the cockpit is all business — self-bailing, bench seating, rod holders, and a rocket-launcher rack overhead.",
      "Power is a single Mercury 175XL. The hours are honest at 1,505, and the selling dealer makes the argument that matters: this engine has been run and maintained rather than left to sit. Every oil and impeller change is documented, cylinder compression and engine test results are available, and the full service history comes from the dealer's own technicians.",
      "She is offered at $70,000 with a one-year manufacturer-backed warranty still in force — genuinely unusual on a used boat, and the reason this one is worth seeing before the private-party listings. In the water at Tacoma and available for viewing and sea trial.",
    ],
    highlights: [
      "2023 Defiance San Juan 220 — one owner",
      "Mercury 175XL outboard · 1,505 hours",
      "1-year manufacturer-backed warranty",
      "Full composite build — no wood coring",
      "Complete service records since new",
      "Compression & engine test results on file",
      "Hardtop pilothouse — side & aft doors",
      "Convertible dinette — drops to a berth",
      "24'6\" · 8'6\" beam · 21° deep-vee",
      "100 gallon fuel capacity",
      "Rocket-launcher rack & cockpit rod holders",
      "Self-bailing cockpit w/ bench seating",
    ],
  },
  "jeanneau-nc-695": {
    slug: "jeanneau-nc-695",
    tagline: {
      lead: "A",
      emphasis: "French-built weekender",
      tail: "— enclosed wheelhouse, two cabins, factory backed.",
    },
    specStrip: [
      { value: "24'5\"", label: "Length" },
      { value: "2022", label: "Year Built" },
      { value: "Mercury", label: "150hp Outboard" },
      { value: "1,100", label: "Engine Hours" },
      { value: "45 gal", label: "Fuel" },
    ],
    narrative: [
      "The Jeanneau NC 695 is the boat that made the NC formula famous — a proper enclosed wheelhouse, a sliding side door, and full standing accommodation, all inside a 24-foot hull light enough to run behind a single 150. This 2022 example has had one owner and has been maintained since new by the Victory Boats service department.",
      "What separates the 695 from other boats this size is that nothing about it feels borrowed from something smaller. The wheelhouse closes up completely against Northwest weather, with a sliding door aft to the cockpit and a second door forward to the side deck. Inside, a solid table and wraparound settee convert to a berth, with a further cabin forward — real overnight accommodation rather than a token cuddy.",
      "Power is a trimmable Mercury 150 with 1,100 hours. The selling dealer has completed a full 77-point inspection and backs the engine with a one-year manufacturer warranty; engine and compression test results are available on request. Navigation is a touchscreen Garmin chartplotter and depth sounder, there is a four-speaker digital audio system, and the bottom has been freshly painted for saltwater use.",
      "Offered at $70,000 — in line with recent comparable sales at similar hours. Sea trial available, with the dealer offering sea-trial satisfaction before final purchase.",
    ],
    highlights: [
      "2022 Jeanneau NC 695 — one owner",
      "Trimmable Mercury 150hp · 1,100 hours",
      "1-year manufacturer-backed engine warranty",
      "Full 77-point dealer inspection completed",
      "Engine & compression test results available",
      "Touchscreen Garmin chartplotter & sounder",
      "Four-speaker digital audio system",
      "Fresh bottom paint — saltwater ready",
      "Enclosed wheelhouse w/ sliding side door",
      "Convertible saloon berth + forward cabin",
      "24'5\" · 8'4\" beam · 18° deadrise",
      "45 gal fuel · WA registered WN 0490 SZ",
    ],
  },
  "miss-maggie-ii": {
    slug: "miss-maggie-ii",
    tagline: {
      lead: "A",
      emphasis: "Down East classic",
      tail: "— Maine built, single-diesel simple.",
    },
    specStrip: [
      { value: "30'5\"", label: "Length" },
      { value: "2016", label: "Year Built" },
      { value: "10'10\"", label: "Beam" },
      { value: "Single", label: "Diesel Inboard" },
      { value: "Down East", label: "Hull Form" },
    ],
    narrative: [
      "Miss Maggie II is a 2016 Back Cove 30 — the boat that defined the modern Down East cruiser. Built in Rockland, Maine, the 30 pairs a single diesel inboard with a soft-riding semi-displacement hull, giving you the look of a classic lobster yacht and the running costs of one engine. She is USCG documented and lies in covered moorage at Edmonds.",
      "Back Cove's reputation rests on how much boat they fit into thirty feet without making it feel crowded. A deep windshield and wraparound glass keep the pilothouse bright and the visibility honest. The helm sits to starboard with a companion settee opposite and a salon that converts for guests. Forward there is a private cabin with a proper V-berth, a separate head with shower, and a galley with refrigeration, stovetop and microwave — everything a couple needs for a week in the San Juans.",
      "The cockpit is deep, self-draining and uncluttered, with easy side-deck access forward. Below the sole a single diesel sits in a clean, well-lit engine space with genuine room to work — the kind of installation that tells you how a boat has been kept. A generator, bow thruster and Espar diesel cabin heat make her a true three-season Northwest boat.",
      "Offered at $325,000. Full documentation, service records and sea trial available on request.",
    ],
    highlights: [
      "2016 Back Cove 30 — built in Rockland, Maine",
      "Single diesel inboard — economical to run",
      "Semi-displacement Down East hull",
      "USCG documented · Official #1270309",
      "Generator & bow thruster",
      "Espar diesel cabin heat",
      "Pilothouse with wraparound glass",
      "Private forward cabin, V-berth",
      "Separate head with shower",
      "Galley — fridge, stovetop & microwave",
      "Deep self-draining cockpit",
      "Covered moorage, Edmonds Marina",
    ],
    documentation: { officialNo: "1270309" },
    photoCredit: "Edmonds Marina, WA",
  },
  jimmie: {
    slug: "jimmie",
    tagline: {
      lead: "A",
      emphasis: "purpose-built aluminum",
      tail: "workboat — Rozema hulled, shellfish rigged.",
    },
    specStrip: [
      { value: "50'0\"", label: "Length" },
      { value: "1997", label: "Year Built" },
      { value: "Aluminum", label: "Welded Hull" },
      { value: "Twin", label: "Outboard Power" },
      { value: "Rozema", label: "Boat Works" },
    ],
    narrative: [
      "Jimmie is a 1997 Rozema 50 — a custom welded-aluminum workboat built for the shellfish industry and still doing the job she was designed for. Rozema Boat Works of Mount Vernon has built aluminum commercial hulls for Pacific Northwest operators for decades, and this is one of their custom oyster boats: a long, flat, unobstructed working deck, shallow draft, and the kind of structure that shrugs off a working life on the tideflats.",
      "The layout is all business. A raised pilothouse sits well aft, leaving the entire foredeck clear for gear, totes and bulk product, with a deck davit for handling loads over the side. Welded aluminum means no core to rot and a hull that tolerates beach work and grid time that would end a fiberglass boat.",
      "Power is twin outboards on the transom — simple to service, straightforward to repower, and friendly to the shallow water this kind of work demands. The pilothouse is functional and uncluttered, with clear sightlines fore and aft for close-quarters deck handling, and the battery bank and systems sit in dry, accessible compartments.",
      "Offered at $1,100,000. USCG documented. Survey, service history and sea trial available on request — serious inquiries welcome.",
    ],
    highlights: [
      "1997 Rozema 50' — custom aluminum build",
      "Rozema Boat Works, Mount Vernon, WA",
      "Welded aluminum hull — no core to rot",
      "Long, unobstructed working foredeck",
      "Deck davit for over-the-side handling",
      "Twin outboard power — simple to service",
      "Shallow draft — tideflat capable",
      "Raised pilothouse, clear sightlines",
      "USCG documented · Official #1065009",
      "Purpose-built for shellfish operations",
      "Accessible battery bank & systems",
      "Lying Seabeck, WA — Hood Canal",
    ],
    documentation: { officialNo: "1065009" },
    photoCredit: "Seabeck, WA",
  },
  "sau-ping": {
    slug: "sau-ping",
    tagline: {
      lead: "A",
      emphasis: "single-owner Sundancer",
      tail: "— joystick docking, boat-show spec.",
    },
    specStrip: [
      { value: "35'0\"", label: "Length" },
      { value: "2021", label: "Year Built" },
      { value: "750hp", label: "Twin MerCruiser 8.2L" },
      { value: "600", label: "Engine Hours" },
      { value: "Joystick", label: "with Skyhook" },
    ],
    narrative: [
      "Sau Ping is a 2021 Sea Ray Sundancer 350 — a single-owner boat ordered as a Seattle Boat Show special with essentially every box ticked. Twin MerCruiser 8.2L V-drive inboards produce 375 horsepower each with just 600 hours logged, and Mercury joystick control with Skyhook alongside a Vetus bow thruster make a 35-foot express cruiser genuinely easy to handle single-handed.",
      "The cockpit is built for entertaining: a large U-shaped settee with filler cushions that convert it into a transom sun pad, a chaise lounge to port of the helm, double swivel helm chairs with flip-up bolsters, and a beverage centre with Kenyon electric grill, Dometic refrigerator and sink. Upgraded SeaDek runs through the cockpit and out onto the extended swim platform. Overhead sits a hardtop sunroof with blue accent lighting and a retractable six-foot SureShade awning, and the full canvas enclosure with upgraded isinglass — a $26,000 factory upgrade — pushes the season well past Labor Day.",
      "Below there are three separate sleeping areas: a forward queen with privacy curtain, a salon settee that converts to a midship berth, and an aft queen that splits into two twins. The galley carries refrigerator, microwave, stovetop and sink, and the head has a Vacuflush toilet, vessel sink and a fully separate shower stall — genuinely hard to find at thirty-five feet.",
      "Navigation is a Simrad 14-inch touchscreen with charts, radar, GPS and sonar alongside SmartCraft engine control. A Westerbeke generator, Fusion stereo with ten Kicker Coastal speakers, three Samsung televisions and an Intervac central vacuum round out the package. Offered at $400,000, lying Des Moines Marina.",
    ],
    highlights: [
      "2021 Sea Ray Sundancer 350 — single owner",
      "Twin MerCruiser 8.2L V-drives · 750hp",
      "600 hours logged",
      "Mercury joystick control with Skyhook",
      "Vetus bow thruster",
      "Simrad 14\" touchscreen — radar, GPS, sonar",
      "Westerbeke generator",
      "$26,000 full canvas enclosure upgrade",
      "Hardtop sunroof & retractable SureShade",
      "SeaDek cockpit & extended swim platform",
      "Three sleeping areas — forward, salon, aft",
      "Separate shower stall in the head",
    ],
    photoCredit: "Puget Sound, WA",
  },
  "nc-695-weekender": {
    slug: "nc-695-weekender",
    tagline: {
      lead: "A",
      emphasis: "trailerable weekender",
      tail: "— enclosed wheelhouse, trailer included.",
    },
    specStrip: [
      { value: "21'2\"", label: "Hull Length" },
      { value: "2019", label: "Year Built" },
      { value: "8'4\"", label: "Beam" },
      { value: "Single", label: "Outboard" },
      { value: "Trailer", label: "Included" },
    ],
    narrative: [
      "This 2019 Jeanneau NC 695 Weekender is the boat that proves you do not need forty feet to cruise properly. The NC formula puts a genuinely enclosed wheelhouse, a sliding side door and real overnight accommodation into a hull short enough to tow behind a properly rated vehicle — and she comes with her Pacific tandem-axle trailer included in the sale.",
      "The wheelhouse closes up completely against weather, with a sliding door aft to the cockpit and a second door forward to the side deck for line handling. Inside, the saloon table and wraparound settee drop down to form a berth, with a further cabin forward. It is the layout that made the NC range Jeanneau's best-selling powerboat line, and it works as well on Puget Sound as it does in the Med.",
      "Outboard power keeps things simple: nothing under the sole to service, an easy repower path down the road, and shallow draft when you want to nose into a beach. Deck hardware is straightforward and the hardtop carries the model's signature wraparound glass, so visibility from the helm is excellent in close quarters.",
      "Offered at $72,000 with the trailer. That combination — enclosed wheelhouse, sleeping accommodation, and the freedom to tow her to new water — is genuinely hard to find at this price. Sea trial available on request.",
    ],
    highlights: [
      "2019 Jeanneau NC 695 Weekender",
      "Pacific tandem-axle trailer included",
      "Enclosed wheelhouse — sliding side door",
      "Convertible saloon berth + forward cabin",
      "Single outboard — simple to service",
      "Wraparound hardtop glazing",
      "Trailerable — cruise beyond your home port",
      "21'2\" hull · 8'4\" beam",
      "Shallow draft for beaching",
      "Second forward door for line handling",
      "Jeanneau's best-selling powerboat range",
      "Stored ashore under cover",
    ],
  },
  "cobalt-343": {
    slug: "cobalt-343",
    tagline: {
      lead: "A",
      emphasis: "181-hour Cobalt",
      tail: "— flagship 343, original paperwork intact.",
    },
    specStrip: [
      { value: "35'4\"", label: "Length" },
      { value: "2005", label: "Year Built" },
      { value: "Twin", label: "MerCruiser Power" },
      { value: "181", label: "Engine Hours" },
    ],
    narrative: [
      "This 2005 Cobalt 343 Performance Cruiser shows just 181 hours on the meter. Cobalt built the 343 as the flagship of its cruiser line, and the company's reputation for build quality is the reason a twenty-year-old boat still presents the way this one does. She retains her original window sticker, owner's manuals and keys, and was delivered new through Seattle Boat Company.",
      "Twin MerCruiser power sits beneath a power-assisted engine hatch in a clean, well-lit bay with diamond-plate step surfaces and genuine access all round — the kind of engine room that makes a surveyor's job easy. The cockpit is pure Cobalt: deep wraparound seating, faux-teak decking through the sole and out onto the swim platform, and a broad transom sun pad. Forward, the foredeck opens up as a second lounging area with its own cushioning.",
      "A deep-vee hull of this size is what Cobalt does best — a dry, confident ride through the short chop Puget Sound serves up on a summer afternoon, with enough beam to carry a crowd without anyone feeling crowded. She lies at Madrona Marina, Washington registered.",
      "Offered at $89,000. Original documentation, service history and sea trial available on request.",
    ],
    highlights: [
      "2005 Cobalt 343 Performance Cruiser",
      "Just 181 hours indicated",
      "Twin MerCruiser power",
      "Original window sticker & manuals retained",
      "Delivered new by Seattle Boat Company",
      "Deep-vee performance cruiser hull",
      "Power-assisted engine hatch",
      "Faux-teak decking, cockpit & platform",
      "Transom sun pad + foredeck lounge",
      "Hull No. FGE34056C505",
      "WA registered WN 4054 NS",
      "Lying Madrona Marina",
    ],
    photoCredit: "Madrona Marina, WA",
  },
  "ocean-alexander-548": {
    slug: "ocean-alexander-548",
    tagline: {
      lead: "A",
      emphasis: "proper pilothouse",
      tail: "motoryacht — teak joinery, twin diesels.",
    },
    specStrip: [
      { value: "548", label: "Ocean Alexander" },
      { value: "1996", label: "Year Built" },
      { value: "Twin", label: "Diesel Inboard" },
      { value: "2", label: "Staterooms" },
      { value: "Flybridge", label: "& Pilothouse" },
    ],
    narrative: [
      "This 1996 Ocean Alexander 548 is the kind of boat the Pacific Northwest was made for. Ocean Alexander built their reputation on heavily-built, teak-joined pilothouse motoryachts that could run the Inside Passage in comfort, and the 548 sits right in the sweet spot of that lineage — big enough to live aboard for a season, small enough for a couple to run.",
      "The saloon is finished in warm teak with a large L-shaped settee, opposing armchairs and windows on three sides. Forward and up, a true pilothouse gives you a raised helm with a settee behind it — the place you will actually spend your time when the weather turns. The galley sits down and forward, laid out for real cooking rather than reheating.",
      "Accommodation is two staterooms and two heads: a full-beam master with a walkaround berth and en-suite, and a guest cabin with twin berths and its own head with separate shower stall. Below, a walk-in engine room houses twin diesels with standing access down the centreline and clean, labelled electrical distribution — the sort of engine space that says a boat has been maintained rather than merely used.",
      "Topside, the flybridge carries Furuno radar, a second helm and generous seating, with a broad foredeck forward. A serious cruising platform, offered at $575,000. Survey, service history and sea trial available on request.",
    ],
    highlights: [
      "1996 Ocean Alexander 548",
      "Twin diesel inboards — walk-in engine room",
      "True raised pilothouse with helm settee",
      "Flybridge helm with Furuno radar",
      "Two staterooms, two heads",
      "Full-beam master with walkaround berth",
      "Guest cabin with twin berths",
      "Separate shower stall",
      "Teak joinery throughout the saloon",
      "Galley laid out for real cooking",
      "Clean, labelled electrical distribution",
      "Broad foredeck & generous flybridge seating",
    ],
  },
};

export function getBrochure(slug: string): BrochureContent | undefined {
  return brochures[slug];
}
