#!/usr/bin/env python3
"""Render a portable branded review from a local draft. Does not publish or send."""
import base64,html,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def esc(s):return html.escape(str(s))
def data(url):
 p=ROOT/'public'/url.lstrip('/');mime='image/png' if p.suffix=='.png' else 'image/jpeg'
 return 'data:'+mime+';base64,'+base64.b64encode(p.read_bytes()).decode()
d=json.loads(Path(sys.argv[1]).read_text());a=d['article'];catalog={x['id']:x for x in json.loads((ROOT/'src/lib/newsletter/image-catalog.json').read_text())};images=[{**catalog[x['id']],**x} for x in d['images']]
assert len(images)==len(a['sections'])+2
def photo(i):
 p=images[i]
 return '<figure><img src="'+data(p['url'])+'" alt="'+esc(p['alt'])+'"><figcaption>'+esc(p['caption'])+'<span>'+esc(p['credit'])+' · <a href="'+esc(p['source'])+'">Source</a>'+(' · <a href="'+esc(p['licenseUrl'])+'">'+esc(p['license'])+'</a>' if p.get('licenseUrl') else '')+'</span></figcaption></figure>'
css='''*{box-sizing:border-box}body{margin:0;background:#07111b;color:#142333;font-family:Arial,sans-serif}a{color:inherit;text-underline-offset:3px}.journal{max-width:1160px;margin:auto;background:#f7f4ed}.masthead{background:#0c1b2a;color:white;text-align:center;padding:42px 35px 38px}.logo{width:104px;height:104px}.kicker{font-size:10px;letter-spacing:4px;text-transform:uppercase;color:#b99d6d}.masthead .kicker{margin-top:24px}.edition{display:flex;justify-content:space-between;border-top:1px solid #54606a;margin-top:28px;padding-top:18px;font-size:10px;letter-spacing:2px;text-transform:uppercase;color:#bdc6cd}.title{padding:55px 7% 36px}h1,h2,h3{font-family:Georgia,serif;font-weight:normal}h1{font-size:clamp(38px,5vw,66px);line-height:1.08;margin:20px 0}h2{font-size:clamp(30px,3vw,43px);line-height:1.12;margin:14px 0 26px}h3{font-size:24px;line-height:1.25;margin:0 0 14px}.dek{max-width:630px;font-size:16px;line-height:1.8;color:#5a6670}figure{margin:0}figure img{width:100%;height:auto;display:block;max-height:650px;object-fit:contain;background:#e9e4db}figcaption{margin-top:12px;border-left:2px solid #b99d6d;padding-left:12px;font-size:11px;line-height:1.7;color:#66717a}figcaption span{display:block;font-size:10px;margin-top:4px}.hero{padding:0 4%}.lead{padding:40px 8% 48px;font-family:Georgia,serif;font-size:23px;line-height:1.7}.lead p{margin:0}.section{padding:48px 8%;border-top:1px solid #d9cdb7}.copy{font-size:16px;line-height:1.9}.copy p{margin:24px 0 0}.section.split .spread{display:grid;grid-template-columns:1fr 1fr;gap:40px;align-items:start}.section.split:nth-of-type(even) figure{order:2}.section.split figure img{max-height:550px}.section.split .copy p:first-child{margin-top:0}.questions{background:#122535;color:#f6f3ed;padding:50px 8%}.questions .kicker{color:#c9ab76}.questions figcaption{color:#aebac3}.questions figure{margin-bottom:35px}.question{border-top:1px solid #52616b;padding:26px 0 0;margin:26px 0}.question p{font-size:15px;line-height:1.8;color:#c9d0d6}.cta{padding:42px 8%;display:flex;align-items:center;justify-content:space-between;gap:25px}.cta h2{font-size:34px;margin:0 0 12px}.button{display:inline-block;background:#122535;color:white;padding:17px 24px;white-space:nowrap;font-size:12px;text-decoration:none}.sources{padding:30px 8%;border-top:1px solid #d9cdb7;font-size:11px;color:#5e6a73;line-height:1.9}.sources ul{padding-left:18px}.footer{background:#0c1b2a;padding:30px;text-align:center;color:#b99d6d;font-size:10px;letter-spacing:2px}@media(max-width:650px){.masthead{padding:28px 20px}.edition{font-size:8px;letter-spacing:1px}.title{padding:32px 6% 24px}.hero{padding:0}.hero figcaption{margin-left:6%;margin-right:6%}.lead{font-size:21px;padding:30px 6%}.section{padding:34px 6%}.section.split .spread{display:flex;flex-direction:column;gap:22px}.section.split:nth-of-type(even) figure{order:0}.questions{padding:34px 6%}.cta{display:block;padding:34px 6%}.button{margin-top:20px}h2{font-size:33px}}'''
body='<div class="journal"><header class="masthead"><img class="logo" src="'+data('/brand/logo-nav.png')+'" alt="Gray Yachts"><p class="kicker">The Gray Yachts Journal</p><div class="edition"><span>International yacht shows</span><span>September 24, 2026 · Review edition</span></div></header><div class="title"><p class="kicker">Monaco / The day-two briefing</p><h1>Monaco, in focus.</h1><p class="dek">'+esc(a['excerpt'])+'</p></div><div class="hero">'+photo(0)+'</div><div class="lead"><p>'+esc(a['introduction'])+'</p></div>'
for i,s in enumerate(a['sections']):body+='<section class="section '+('split' if i>=2 else '')+'"><p class="kicker">'+str(i+1).zfill(2)+' / The briefing</p><h2>'+esc(s['heading'])+'</h2><div class="spread">'+photo(i+1)+'<div class="copy">'+''.join('<p>'+esc(p)+'</p>' for p in s['paragraphs'])+'</div></div></section>'
body+='<section class="questions"><p class="kicker">The owner’s notebook</p><h2>Questions worth asking.</h2>'+photo(len(images)-1)+''.join('<div class="question"><h3>'+esc(q['question'])+'</h3><p>'+esc(q['answer'])+'</p></div>' for q in a['questions'])+'</section><section class="cta"><div><h2>Your next chapter on the water.</h2><p class="dek">Talk with Connor Gray about your boat and your plans.</p></div><a class="button" href="https://grayyachts.com/sell">Discuss your yacht →</a></section><aside class="sources"><p class="kicker">Reporting & photograph credits</p><ul>'+''.join('<li><a href="'+esc(s['url'])+'">'+esc(s['title'])+'</a></li>' for s in d['sources'])+'</ul><p>Prepared from published sources. Image captions distinguish event archives, location photographs and illustrative boating imagery. No claim of on-site reporting.</p></aside><footer class="footer">GRAY YACHTS · CONNOR GRAY · PACIFIC NORTHWEST</footer></div>'
Path(sys.argv[2]).write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(a['title'])+'</title><style>'+css+'</style></head><body>'+body+'</body></html>')
