/* eslint-disable @next/next/no-img-element */
import type {Metadata} from "next";
import Link from "next/link";
import {ArrowRight} from "lucide-react";
import {campaignYachts} from "@/lib/campaign-yachts";
import {vessels} from "@/lib/fleet";
import YachtInquiryForm from "@/components/marketing/yacht-inquiry-form";
import DiscoveryInventory from "@/components/marketing/discovery-inventory";
const heading="font-[family-name:var(--font-cormorant)]";
const button="inline-flex min-h-12 items-center justify-center gap-4 bg-[#d8bd8c] px-7 py-4 text-xs font-semibold uppercase tracking-[.15em] text-[#101c28] transition-colors hover:bg-[#e7cfaa]";
export const metadata:Metadata={title:"Find Your Life on the Water | Yacht Ownership | Gray Yachts",description:"Discover Jeff Brown Yachts inventory, classic brokerage boats and a personal path to ownership with Connor Gray. Explore yachts and qualifying business-use tax planning.",alternates:{canonical:"https://grayyachts.com/yachts"},openGraph:{title:"Less someday. More life on the water.",description:"Find your yacht. Plan your ownership. Make the most of the journey.",images:["/images/campaign-yachts/sirena-48-aerial.jpg"]}};
export default function Page(){return <div className="bg-[#f7f4ee] text-[#172c3b]">
 <section className="relative isolate overflow-hidden bg-[#091421] px-6 pb-16 pt-40 text-white md:pb-24 md:pt-48 lg:px-12">
  <img src="/images/campaign-yachts/sirena-48-aerial.jpg" alt="Sirena 48 sistership at sea" fetchPriority="high" width={1600} height={1067} className="absolute inset-0 -z-20 h-full w-full object-cover"/>
  <div className="absolute inset-0 -z-10 bg-gradient-to-r from-[#06101b]/95 via-[#06101b]/65 to-[#06101b]/20"/>
  <div className="mx-auto max-w-6xl"><p className="text-xs uppercase tracking-[.25em] text-[#e2c99e]">Gray Yachts · Your next chapter</p>
   <h1 className={`${heading} mt-6 max-w-3xl text-6xl leading-[.95] md:text-8xl`}>Less someday.<br/><em className="font-normal text-[#e2c99e]">More life on the water.</em></h1>
   <p className="mt-7 max-w-xl text-lg leading-8 text-white/85">Coffee in a quiet cove. A table full of friends. A weekend you wish would last a little longer. Let’s find the yacht that brings it all closer.</p>
   <div className="mt-8 flex flex-wrap gap-4"><a href="#collection" className={button}>Find your yacht <ArrowRight size={16}/></a><a href="#ownership" className="inline-flex items-center border border-white/45 px-7 py-4 text-xs uppercase tracking-widest">Plan your ownership</a></div>
   <div className="mt-10 max-w-2xl border-l-2 border-[#d8bd8c] bg-[#081422]/80 p-6 backdrop-blur-sm"><p className="text-lg font-semibold text-[#e2c99e]">Could yacht ownership work with your tax plan?</p><p className="mt-2 text-sm leading-6 text-white/85">Qualifying business use may offer tax deductions. We’ll help you explore the yacht and ownership plan, working alongside your CPA to evaluate the opportunity before you buy.</p><a href="#tax-planning" className="mt-3 inline-block text-sm text-[#e2c99e] underline underline-offset-4">Explore the possibilities and requirements →</a></div>
   <p className="mt-6 text-[10px] text-white/60">Sirena 48 sistership shown</p>
  </div>
 </section>
 <nav aria-label="Explore yacht ownership" className="border-b border-[#172c3b]/15 bg-[#f7f4ee] px-6"><div className="mx-auto flex max-w-6xl flex-wrap gap-x-9 gap-y-2 py-5 text-sm font-medium">{[['The experience','#experience'],['Featured yachts','#featured'],['All yachts & brands','#collection'],['Classic boats','#classics'],['Ownership & tax planning','#tax-planning']].map(([label,href])=><a key={href} href={href} className="py-2 hover:underline underline-offset-8">{label}</a>)}</div></nav>
 <section id="experience" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-20 md:py-28"><p className="text-xs uppercase tracking-[.2em] text-[#806332]">Start with the life you want</p><h2 className={`${heading} mt-4 max-w-3xl text-5xl md:text-6xl`}>The best part isn’t owning a yacht.<br/><em>It’s being aboard.</em></h2>
  <div className="mt-12 grid gap-8 md:grid-cols-3">{[
   ['A weekend becomes a getaway.','Trade the usual routine for slow mornings, a new harbor and a little more time together.','/images/campaign-yachts/sirena-48-3.jpg','Sirena 48 sistership flybridge dining area'],
   ['Make getting there the occasion.','Feel the coast open up ahead of you. Find a boat with the design and energy that make every departure feel special.','/images/campaign-yachts/pershing-6x-running.jpg','Pershing 6X sistership underway'],
   ['Bring your favorite people.','Long lunches, swimming off the stern, stories that carry on after sunset. Choose the spaces that make everyone feel at home.','/images/campaign-yachts/pershing-6x-2.jpg','Pershing 6X sistership salon']
  ].map(([title,text,image,alt])=><article key={title}><img src={image} alt={alt} loading="lazy" width={800} height={600} className="aspect-[4/3] w-full object-cover"/><h3 className={`${heading} mt-6 text-3xl`}>{title}</h3><p className="mt-3 leading-7 opacity-80">{text}</p></article>)}</div><p className="mt-4 text-[10px] opacity-60">Lifestyle photographs show Sirena and Pershing sisterships.</p>
 </section>
 <section id="featured" className="scroll-mt-24 bg-[#0b1724] px-6 py-20 text-[#f7f4ee]"><div className="mx-auto max-w-6xl"><p className="text-xs uppercase tracking-[.2em] text-[#d8bd8c]">Two places to begin</p><h2 className={`${heading} mt-4 text-5xl md:text-6xl`}>Which weekend looks like yours?</h2><div className="mt-10 grid gap-10 md:grid-cols-2">{campaignYachts.map(y=><Link key={y.slug} href={'/yachts/'+y.slug} className="group"><img src={y.photos[0].src} alt={y.photos[0].alt} width={1000} height={700} loading="lazy" className="aspect-[4/3] w-full object-cover"/><p className="mt-5 text-xs uppercase tracking-widest text-[#d8bd8c]">{y.slug==='sirena-48'?'Stay a little longer':'Italian performance'}</p><h3 className={`${heading} mt-2 text-5xl`}>{y.name}</h3><p className="mt-3 leading-7 text-white/75">{y.intro}</p><p className="mt-5 text-2xl font-bold text-[#d8bd8c]">{y.estimatedPrice}</p><p className="mt-2 text-xs text-white/60">Estimated budget · USD · Confirm current pricing · Sistership shown</p><p className="mt-6 inline-flex items-center gap-4 border-b border-[#d8bd8c] pb-2 text-sm">Step aboard. Watch the film. <ArrowRight size={17}/></p></Link>)}</div></div></section>
 <section id="collection" className="mx-auto max-w-6xl scroll-mt-24 px-6 py-20 md:py-28"><p className="text-xs uppercase tracking-[.2em] text-[#806332]">The Jeff Brown Yachts collection</p><h2 className={`${heading} mt-4 text-5xl md:text-6xl`}>One invitation.<br/><em>A world of possibilities.</em></h2><p className="my-7 max-w-2xl text-lg leading-8 opacity-80">From Axopar adventures and Everglades fishing trips to Riva elegance, Sirena cruising and Pershing performance. Explore the collection, then let Connor help you narrow it down.</p><p className="mb-9 text-sm leading-6 opacity-70">Discover Axopar, BRABUS Marine, Everglades, Four Winns, Jeanneau, Pershing, Riva, Sirena and Wally, plus brokerage yachts from other builders. Representation varies by office and territory. <Link href="/brands" className="underline">Explore all nine featured brands →</Link></p><DiscoveryInventory/></section>
 <section id="classics" className="scroll-mt-24 border-y border-[#172c3b]/15 bg-[#ece8df] px-6 py-20"><div className="mx-auto max-w-6xl"><p className="text-xs uppercase tracking-[.2em] text-[#806332]">Character never goes out of style</p><h2 className={`${heading} mt-4 text-5xl`}>A different kind of love story.</h2><p className="mt-5 max-w-2xl leading-8">A traditional sloop. A welcoming pilothouse. The familiar lines of a coastal cruiser. Explore these Gray Yachts brokerage boats for another way to make the water part of your life.</p><div className="mt-10 grid gap-8 md:grid-cols-3">{['seawulff','ocean-alexander-548','miss-maggie-ii'].map(slug=>vessels.find(v=>v.slug===slug)).filter(v=>v!==undefined).map(v=><Link href={'/fleet/'+v.slug} key={v.slug}><img src={v.image} alt={`${v.year} ${v.make} ${v.name}`} width={800} height={600} loading="lazy" className="aspect-[4/3] w-full object-cover"/><p className="mt-5 text-xs uppercase tracking-widest">{v.year} · {v.length}</p><h3 className={`${heading} mt-2 text-3xl`}>{v.make}</h3><p className="mt-2">{v.name}</p><p className="mt-3 text-xl font-semibold">{v.price}</p><p className="mt-4 text-sm underline underline-offset-4">Discover her story →</p></Link>)}</div><p className="mt-7 text-xs opacity-65">Brokerage availability and asking prices require confirmation. Boats are shown as listed, not as new-build dealer offerings.</p></div></section>
 <section id="tax-planning" className="mx-auto grid max-w-6xl scroll-mt-24 gap-12 px-6 py-20 md:grid-cols-2 md:py-28"><div><p className="text-xs uppercase tracking-[.2em] text-[#806332]">A thoughtful approach to ownership</p><h2 className={`${heading} mt-4 text-5xl md:text-6xl`}>Love the lifestyle.<br/><em>Understand the numbers.</em></h2><p className="mt-6 text-lg leading-8">Qualifying yacht business use may create meaningful tax deductions. Let’s explore the ownership possibilities alongside the boat itself.</p><a href="#contact-connor" className={button+' mt-8'}>Discuss your ownership plan <ArrowRight size={16}/></a></div><div className="border border-[#172c3b]/20 p-7 md:p-9"><h3 className={`${heading} text-3xl`}>Potential benefits. A plan grounded in your situation.</h3><p className="mt-5 leading-7">Eligible business-use property may qualify for up to <strong>100% first-year bonus depreciation on its eligible basis</strong>. A yacht must independently meet the applicable requirements; this is not a promise of eligibility or savings.</p><p className="mt-4 leading-7">Connor helps with yacht selection and the purchase process. Your CPA evaluates the proposed activity, business-use allocation, timing, records and applicable limits before you commit.</p><p className="mt-5 text-sm leading-6 opacity-80">Deductions reduce taxable income—not taxes dollar for dollar. Personal recreation and ordinary client entertainment generally do not qualify. An LLC or a business sale alone does not establish eligibility. Loss limitations and recapture can affect the result. No tax benefit has been established for any yacht shown.</p><p className="mt-5 text-xs leading-6"><a href="https://www.irs.gov/publications/p946" className="underline">IRS depreciation requirements</a> · <a href="https://www.irs.gov/publications/p463" className="underline">IRS entertainment-use rules</a></p></div></section>
 <section id="ownership" className="bg-[#0b1724] px-6 py-20 text-[#f7f4ee]"><div className="mx-auto max-w-6xl"><p className="text-xs uppercase tracking-[.2em] text-[#d8bd8c]">From the first conversation to the first departure</p><h2 className={`${heading} mt-4 text-5xl md:text-6xl`}>An easier path to your yacht.</h2><div className="mt-12 grid gap-10 md:grid-cols-3">{[['01','Tell me about your perfect day.','Where you want to go, who’s coming along, and what you want ownership to feel like. We’ll start there.'],['02','Build your shortlist and your plan.','Compare boats, ownership costs and practical needs. Bring your CPA into any business-use planning early.'],['03','Move forward with guidance.','Coordinate viewings, offers, surveys and closing steps, then discuss delivery, familiarization and service resources.']].map(([n,title,text])=><div key={n}><p className="text-[#d8bd8c]">{n}</p><h3 className={`${heading} mt-5 text-3xl`}>{title}</h3><p className="mt-4 leading-7 text-white/70">{text}</p></div>)}</div></div></section>
 <section id="contact-connor" className="scroll-mt-24 bg-[#101c2b] px-6 py-20 text-[#f7f4ee]"><div className="mx-auto grid max-w-6xl gap-12 md:grid-cols-2"><div><p className="text-xs uppercase tracking-[.2em] text-[#d8bd8c]">Your next chapter starts with a conversation</p><h2 className={`${heading} mt-4 text-5xl`}>What would you love<br/><em>to do on the water?</em></h2><p className="mt-6 max-w-md leading-8 text-white/75">Tell me a little about your plans. I’ll help you explore the boats, the practical details and the questions to discuss with your tax adviser.</p><div className="mt-8 flex items-center gap-5"><img src="/connor-gray-sm.jpeg" alt="Connor Gray" width={80} height={80} className="h-20 w-20 rounded-full object-cover"/><div><p className={`${heading} text-3xl`}>Connor Gray</p><p className="text-xs uppercase tracking-widest text-[#d8bd8c]">Gray Yachts · Seattle</p></div></div><p className="mt-6 leading-8"><a href="tel:+14256718474">425-671-8474</a><br/><a href="mailto:grayyachts@gmail.com">grayyachts@gmail.com</a></p></div><YachtInquiryForm yacht="yacht ownership plan"/></div></section>
 </div>}
