import brandPhotos from '../../../../content/seo/brand-images.json';
import PostThumbnail, {type EditorialPhoto} from '@/components/marketing/post-thumbnail';
import brands from '../../../../content/seo/brands.json';
import { pageMetadata } from '@/lib/editorial';
import { EditorialShell, SellerContact } from '@/components/marketing/editorial';
export const metadata=pageMetadata('JBY featured yacht brands | Sirena, BRABUS, Axopar, Riva & Pershing | Gray Yachts','Explore Jeff Brown Yachts brands: Sirena, BRABUS Marine, Axopar, Riva, Pershing, Wally, Everglades, Four Winns and Jeanneau, with photographs and regional availability notes.','/brands');
function BrandCard({brand:b}:{brand:typeof brands[number]}) {
 return <article id={b.id} className="group rounded-xl border border-border bg-bg-card p-7"><PostThumbnail photo={(brandPhotos as Record<string,EditorialPhoto>)[b.id]}/><p className="text-xs uppercase tracking-widest text-gold">{b.category}</p><h3 className="mt-3 font-[family-name:var(--font-cormorant)] text-3xl">{b.name}</h3>{b.group==='jby'&&<p className="mt-3 text-xs leading-5 text-gold/80">JBY · {b.region}</p>}<p className="mt-4 leading-7 text-text-secondary">{b.update}</p><p className="mt-4 leading-7 text-text-secondary">{b.angle}</p><a href={b.jbySource||b.sourceUrl} className="mt-5 inline-block text-sm text-gold underline underline-offset-4">{b.group==='jby'?(b.id==='jeanneau'?'View JBY in Jeanneau’s dealer directory':'Explore at Jeff Brown Yachts'):'Manufacturer source'}</a><p className="mt-2 text-xs text-text-secondary">Checked {b.checkedAt}</p></article>;
}
export default function BrandsPage(){return <EditorialShell eyebrow="Featured boat brands" title="Find your next chapter." intro="Explore the brands represented by Jeff Brown Yachts, from adventure boats and offshore fishing boats to sailing yachts and Italian motor yachts.">
 <section aria-labelledby="jby-brands"><div className="mb-8"><p className="text-xs uppercase tracking-[0.2em] text-gold">The JBY portfolio</p><h2 id="jby-brands" className="mt-3 font-[family-name:var(--font-cormorant)] text-4xl">Nine brands. Different ways to get on the water.</h2><p className="mt-4 max-w-3xl text-sm leading-7 text-text-secondary">Start with how you plan to use the boat. JBY’s represented brands vary by coast and office; confirm the particular model and territory with Connor. The lineup below is checked against <a href="https://jeffbrownyachts.com/brands" className="text-gold underline">JBY’s brand directory</a> and <a href="https://www.jeanneau.com/en-us/agencies/1263-jeff-brown-yachts-wrightsville" className="text-gold underline">Jeanneau’s dealer directory</a>.</p></div><div className="grid gap-6 md:grid-cols-2">{brands.filter(b=>b.group==='jby').map(b=><BrandCard key={b.id} brand={b}/>)}</div></section>
 <section className="mt-20" aria-labelledby="research-brands"><p className="text-xs uppercase tracking-[0.2em] text-gold">Beyond the portfolio</p><h2 id="research-brands" className="mt-3 font-[family-name:var(--font-cormorant)] text-4xl">Other builders we’re following.</h2><p className="mb-8 mt-4 max-w-3xl text-sm leading-7 text-text-secondary">Independent editorial coverage of emerging and specialist builders. These are not presented as JBY dealerships. Manufacturer information is attributed; it is not an independent sea trial.</p><div className="grid gap-6 md:grid-cols-2">{brands.filter(b=>b.group!=='jby').map(b=><BrandCard key={b.id} brand={b}/>)}</div></section><SellerContact/></EditorialShell>}
