/* eslint-disable @next/next/no-img-element -- Existing optimized static assets are served directly by Cloudflare. */
import Link from 'next/link';
import EditorialTabs from '@/components/marketing/editorial-tabs';
import PostThumbnail, {type EditorialPhoto} from '@/components/marketing/post-thumbnail';
import type {Issue} from '@/lib/newsletter/core';
function cover(issue:Issue):EditorialPhoto {const photo=JSON.parse(issue.images||'[]')[0];return photo||{url:issue.hero,alt:issue.title,credit:'Gray Yachts brokerage photography'};}

import {ArrowUpRight, ArrowRight} from 'lucide-react';
import type {Metadata} from 'next';
import {publishedIssues} from '@/lib/newsletter/db';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'The Gray Yachts newsletter | Buying & selling in the PNW',description:'Practical guidance for buying and selling yachts in the Pacific Northwest. Read the Gray Yachts newsletter, from choosing your next boat to preparing yours for sale.',alternates:{canonical:'https://grayyachts.com/newsletter'}};
export default async function NewsletterPage() {
 const issues=await publishedIssues();
 const featured=issues[0];
 return <main>
  <section className="relative min-h-[660px] overflow-hidden flex items-end bg-[#091722]">
   {/* Existing original brokerage photography, used as an atmospheric cover. */}
   
   <img src="/sell/img/hero.jpg" alt="Yacht on the water" className="absolute inset-0 h-full w-full object-cover opacity-50" fetchPriority="high"/>
   <div className="absolute inset-0 bg-gradient-to-t from-[#060a12] via-[#060a12]/30 to-[#060a12]/40"/>
   <div className="relative mx-auto w-full max-w-7xl px-6 pt-32 pb-20 md:px-12"><EditorialTabs className="mb-12"/><div className="flex items-center gap-4 text-xs tracking-[0.25em] text-[#d8bd8c]"><span className="h-px w-12 bg-[#d8bd8c]"/>THE GRAY YACHTS NEWSLETTER</div><h1 className="mt-7 max-w-4xl font-[family-name:var(--font-cormorant)] text-6xl md:text-8xl leading-[0.98] text-[#f7f4ee]">Your next chapter<br/><span className="italic text-[#d8bd8c]">on the water.</span></h1><p className="mt-8 max-w-xl text-lg leading-relaxed text-slate-200">International yacht shows, featured boat brands and practical guidance for buying, selling and owning a yacht.</p><a href="#latest" className="mt-9 inline-flex items-center gap-4 text-sm text-[#e4c99c]">Read the newsletter <ArrowRight size={18}/></a></div>
  </section>
  <div className="bg-[#f7f4ee] text-[#162636]">
   <section id="latest" className="mx-auto max-w-7xl px-6 py-16 md:px-12 md:py-24 scroll-mt-20"><div className="mb-10 flex flex-wrap items-end justify-between gap-5 border-b border-[#162636]/20 pb-6"><div><p className="text-[11px] uppercase tracking-[0.25em] text-[#756447]">From the brokerage</p><h2 className="mt-3 font-[family-name:var(--font-cormorant)] text-4xl md:text-5xl">The latest edition</h2></div><span className="text-sm text-slate-500">For buyers. For sellers. For what comes next.</span></div>
   {featured ? <div><Link href={`/newsletter/${featured.slug}`} className="group grid gap-8 md:grid-cols-[1.2fr_1fr] md:gap-14 items-center"><img src={featured.hero} alt={cover(featured).alt} className="aspect-[4/3] w-full object-cover"/><div><p className="text-xs uppercase tracking-[0.18em] text-[#756447]">{featured.audience==='seller'?'Selling your yacht':'Finding your yacht'} · {new Date(featured.published_at!).toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric',timeZone:'UTC'})}</p><h3 className="mt-5 font-[family-name:var(--font-cormorant)] text-4xl md:text-5xl leading-tight group-hover:text-[#8a6c3d] transition-colors">{featured.title}</h3><p className="mt-5 text-slate-600 leading-relaxed">{featured.excerpt}</p><span className="mt-8 inline-flex items-center gap-3 border-b border-[#ad9163] pb-2 text-sm">Read this edition <ArrowUpRight size={17}/></span></div></Link><p className="mt-3 text-[10px] text-slate-500">{cover(featured).caption} {cover(featured).credit}{cover(featured).source&&<> · <a className="underline" href={cover(featured).source}>Photo source</a></>}{cover(featured).licenseUrl&&<> · <a className="underline" href={cover(featured).licenseUrl}>{cover(featured).license}</a></>}</p></div> : <div className="grid gap-10 md:grid-cols-[1.1fr_1fr] items-center"><div><p className="text-xs uppercase tracking-[0.18em] text-[#756447]">The first edition is on its way</p><h3 className="mt-5 font-[family-name:var(--font-cormorant)] text-4xl md:text-5xl">Good questions.<br/>Better prepared decisions.</h3><p className="mt-6 max-w-lg leading-relaxed text-slate-600">We’re preparing our first brokerage newsletter. Expect useful guidance on pricing your yacht, comparing boats, and making the most of a viewing.</p><a href="mailto:connor@grayyachts.com?subject=Question%20for%20the%20Gray%20Yachts%20newsletter" className="mt-7 inline-flex gap-3 items-center border-b border-[#ad9163] pb-2 text-sm">Send Connor a question <ArrowUpRight size={17}/></a></div><img src="/sell/img/hero.jpg" alt="Yacht on the water" className="aspect-[4/3] w-full object-cover"/></div>}
   {issues.length>1&&<div className="mt-20 grid gap-10 md:grid-cols-2 lg:grid-cols-3">{issues.slice(1).map(issue=><article key={issue.id} className="group border-t border-[#162636]/20 pt-6"><PostThumbnail photo={cover(issue)} href={`/newsletter/${issue.slug}`}/><p className="text-xs uppercase tracking-widest text-[#756447]">{issue.audience==='seller'?'For sellers':'For buyers'}</p><Link href={`/newsletter/${issue.slug}`}><h3 className="mt-4 font-[family-name:var(--font-cormorant)] text-3xl group-hover:text-[#8a6c3d]">{issue.title}</h3><p className="mt-4 text-sm leading-relaxed text-slate-600">{issue.excerpt}</p><span className="mt-6 inline-flex gap-3 text-sm">Read this edition <ArrowUpRight size={18}/></span></Link></article>)}</div>}
   </section>
   <section className="border-t border-[#162636]/15"><div className="mx-auto grid max-w-7xl gap-12 px-6 py-16 md:grid-cols-2 md:px-12"><div><p className="text-xs uppercase tracking-[0.2em] text-[#756447]">Thinking of selling?</p><h2 className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl">Start with your yacht’s value.</h2><p className="mt-4 max-w-md text-slate-600 leading-relaxed">Tell us about your boat and your plans. We’ll help you work through the next steps.</p><a href="/sell" className="mt-7 inline-flex items-center gap-4 bg-[#162636] px-6 py-4 text-sm text-white">Request an evaluation <ArrowUpRight size={17}/></a></div><div><p className="text-xs uppercase tracking-[0.2em] text-[#756447]">Looking for your next boat?</p><h2 className="mt-4 font-[family-name:var(--font-cormorant)] text-4xl">Find a yacht that fits.</h2><p className="mt-4 max-w-md text-slate-600 leading-relaxed">Browse the fleet, take a closer look, and get in touch when something catches your eye.</p><Link href="/fleet" className="mt-7 inline-flex items-center gap-4 border border-[#162636]/30 px-6 py-4 text-sm">Explore the fleet <ArrowUpRight size={17}/></Link></div></div></section>
  </div>
 </main>;
}
