/* eslint-disable @next/next/no-img-element -- Licensed editorial photos retain source credits. */
import type {NewsletterImage} from '@/lib/newsletter/images';
import type {Article} from '@/lib/newsletter/core';
function Photo({photo,lead=false}:{photo:NewsletterImage;lead?:boolean}) {
 return <figure data-newsletter-image={photo.id} className={lead?'mb-12':'my-8'}><div className="overflow-hidden rounded-sm bg-[#e9e4da]"><img src={photo.url} alt={photo.alt} loading={lead?'eager':'lazy'} className="h-auto max-h-[680px] w-full object-contain"/></div><figcaption className="mt-3 border-l-2 border-[#c9a96e] pl-4 text-xs leading-relaxed text-slate-500">{photo.caption}<span className="mt-1 block text-[11px]">{photo.credit} <a href={photo.source} className="underline underline-offset-2">Source</a>{photo.licenseUrl && <> · <a href={photo.licenseUrl} className="underline underline-offset-2">{photo.license}</a></>}</span></figcaption></figure>;
}
export default function NewsletterArticle({article,images=[]}:{article:Article;images?:NewsletterImage[]}) {
 const illustrated=images.length===article.sections.length+2;
 return <div>{images[0]&&<Photo photo={images[0]} lead/>}<p className="border-b border-[#d8c8a8] pb-12 font-[family-name:var(--font-cormorant)] text-2xl leading-relaxed text-slate-800 md:text-3xl">{article.introduction}</p>
  {article.sections.map((section,i)=><section key={section.heading} id={`section-${i}`} className="scroll-mt-28 border-b border-[#d8c8a8] py-12 md:py-16"><p className="mb-4 text-[10px] font-medium uppercase tracking-[0.28em] text-[#8b7045]">{String(i+1).padStart(2,'0')} / The briefing</p><h2 className="max-w-2xl font-[family-name:var(--font-cormorant)] text-4xl leading-[1.08] text-slate-900 md:text-5xl">{section.heading}</h2>{illustrated&&<Photo photo={images[i+1]}/>}<div className="mt-7 space-y-5 text-base leading-[1.9] text-slate-700 md:text-lg">{section.paragraphs.map((p,j)=><p key={j}>{p}</p>)}</div>{!illustrated&&i===1&&images[1]&&<Photo photo={images[1]}/>} {!illustrated&&i===article.sections.length-1&&images[2]&&<Photo photo={images[2]}/>}</section>)}
  <section className="pt-14"><p className="mb-4 text-[10px] uppercase tracking-[0.28em] text-[#8b7045]">The owner’s notebook</p><h2 className="mb-7 font-[family-name:var(--font-cormorant)] text-4xl text-slate-900">Questions worth asking</h2>{illustrated&&<Photo photo={images[images.length-1]}/>}<div className="space-y-7">{article.questions.map((q,i)=><div key={q.question} className="border-l border-[#c9a96e] pl-6"><p className="mb-2 text-[10px] tracking-widest text-[#8b7045]">Q{String(i+1).padStart(2,'0')}</p><h3 className="mb-3 font-[family-name:var(--font-cormorant)] text-2xl text-slate-900">{q.question}</h3><p className="leading-relaxed text-slate-700">{q.answer}</p></div>)}</div></section>
 </div>;
}
