import type { Metadata } from 'next';
export const metadata: Metadata = {title:'Privacy Policy | Gray Yachts',description:'How Gray Yachts handles inquiries, vessel information and connected Gmail data.'};
export default function Privacy(){return <article className="mx-auto max-w-3xl px-6 py-24 text-[#cbd5e1]">
<header className="mb-10 border-b border-[#1e293b] pb-8"><p className="text-sm uppercase tracking-widest text-[#C9A96E]">Gray Yachts</p><h1 className="mt-3 font-[family-name:var(--font-cormorant)] text-5xl text-white">Privacy Policy</h1><p className="mt-4 text-sm">Updated October 8, 2026</p></header>
<div className="space-y-8 text-[15px] leading-relaxed">
<p>This policy describes information handled through Gray Yachts websites, valuation requests and the private Gray Yachts Outreach email application.</p>
<Section title="Inquiries and vessel information"><p>We collect the name, email address, phone number, vessel details, photos and messages you submit. We use them to answer your inquiry, prepare an asking-price comparison, and discuss buying or selling a yacht. Replies may be sent automatically, with personal follow-up from our brokerage. We may retain professional contact information from public business sources for relevant brokerage communications.</p></Section>
<Section title="Website and advertising information"><p>Our website may record referring pages, campaign parameters, advertising click identifiers and interactions with inquiry forms. Where enabled, Meta advertising tools receive event and advertising identifiers. Browser cookies and local storage support site features and campaign measurement. You can manage cookies through your browser settings.</p></Section>
<Section title="Connected Google account"><p>Gray Yachts Outreach is an operator-only application connected to our business Gmail account with the account owner’s permission. It requests Gmail send and read-only access to send brokerage correspondence, check prior correspondence and replies, and prevent duplicate messages. Access includes the connected email address and relevant message metadata and content. We store authorization tokens securely on our server, along with delivery receipts and operational records needed for these features. Website visitors do not need to connect their Google accounts.</p><p className="mt-3">Google user data is used only to operate these communication features. It is not sold, used for advertising targeting, or used to train generalized AI models. Gray Yachts Outreach’s use and transfer of information received from Google APIs adheres to the <a className="text-[#C9A96E] underline" href="https://developers.google.com/terms/api-services-user-data-policy">Google API Services User Data Policy</a>, including its Limited Use requirements.</p></Section>
<Section title="Service providers and sharing"><p>Cloudflare hosts the website; Supabase stores inquiries and related files; Hostinger hosts our automation; and Google and Resend support email delivery. Information passes through these providers as needed to operate the service. Research and extraction providers help find and interpret public vessel listings. We work alongside Jeff Brown Yachts and may share inquiry details when needed to handle a brokerage inquiry or transaction. We may also disclose information when required by law. We do not sell personal information or provide it to unrelated marketers.</p><p className="mt-3">Submitted vessel photos may be served through shareable image URLs for email delivery. Avoid uploading personal documents or other sensitive information in vessel photos. Valuation reports are available to their email recipients and authorized staff.</p></Section>
<Section title="Retention and security"><p>We retain inquiry, correspondence and delivery records as needed to respond, maintain brokerage relationships, prevent duplicate outreach and meet applicable recordkeeping obligations. Access to our operational systems is restricted. No storage or transmission method is completely secure.</p></Section>
<Section title="Your choices"><p>You can ask us to correct or delete information, or stop contacting you, by replying to our email or contacting the address below. Some records may need to be retained for legal or operational obligations. The connected Google account owner can revoke the application’s access through <a className="text-[#C9A96E] underline" href="https://myaccount.google.com/permissions">Google account permissions</a> and request removal of stored authorization and application records. Revoking access does not delete messages already stored in Gmail.</p></Section>
<Section title="Contact"><p><a className="text-[#C9A96E] underline" href="mailto:grayyachts@gmail.com">grayyachts@gmail.com</a><br/>425-671-8474<br/>2288 W Commodore Way, Seattle, WA 98199</p></Section>
<p className="border-t border-[#1e293b] pt-6 text-sm">We will update this page when our information practices change. The separate Marine Tech application has its own <a className="text-[#C9A96E] underline" href="/marine-tech/privacy">privacy policy</a>.</p>
</div></article>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section><h2 className="mb-3 font-[family-name:var(--font-cormorant)] text-2xl text-white">{title}</h2>{children}</section>}
