import {chromium} from 'playwright';
import {createHmac} from 'node:crypto';
import {mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
const base='http://localhost:8792';
const token=id=>createHmac('sha256','local-preview-signing-key-not-for-production-12345').update(`newsletter-review:${id}`).digest('hex');
mkdirSync('/private/tmp/grayyachts-newsletter-checks',{recursive:true});
const browser=await chromium.launch({headless:true});
try {
 const page=await browser.newPage({viewport:{width:1440,height:1100}});
 const response=await page.goto(`${base}/newsletter`);assert.equal(response.status(),200);
 await page.getByRole('heading',{name:'Your next chapter on the water.'}).waitFor();
 assert.equal(await page.locator('a[href="/newsletter/preview-approve"]').count(),0);
 await page.screenshot({path:'/private/tmp/grayyachts-newsletter-checks/desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/private/tmp/grayyachts-newsletter-checks/mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 assert.equal((await page.request.get(`${base}/newsletter/preview-approve`)).status(),404);
 assert.equal((await page.request.get(`${base}/newsletter/review/preview-approve?token=bad`)).status(),404);
 let sitemap=await (await page.request.get(`${base}/newsletter/sitemap.xml`)).text();assert.ok(!sitemap.includes('preview-approve'));
 await page.goto(`${base}/newsletter/review/preview-approve?token=${token('preview-approve')}`);
 await page.getByRole('button',{name:'Approve & publish'}).waitFor();
 assert.equal(await page.locator('meta[name=robots]').getAttribute('content'),'noindex, nofollow');
 await page.screenshot({path:'/private/tmp/grayyachts-newsletter-checks/review.png',fullPage:true});
 assert.equal((await page.request.get(`${base}/newsletter/preview-approve`)).status(),404);
 await page.getByRole('button',{name:'Approve & publish'}).click();
 await page.getByRole('heading',{name:'Published on GrayYachts.com.'}).waitFor();
 assert.equal((await page.request.get(`${base}/newsletter/preview-approve`)).status(),200);
 const replay=await page.request.post(`${base}/api/newsletter/review/preview-approve`,{form:{token:token('preview-approve'),decision:'reject'}});assert.equal(replay.status(),409);
 await page.goto(`${base}/newsletter/review/preview-reject?token=${token('preview-reject')}`);
 await page.getByLabel('Notes for the next draft (optional)').fill('Please add more practical questions.');
 await page.getByRole('button',{name:'Reject draft'}).click();
 await page.getByRole('heading',{name:'Draft rejected. Your feedback is saved for the next issue.'}).waitFor();
 assert.equal((await page.request.get(`${base}/newsletter/preview-reject`)).status(),404);
 sitemap=await (await page.request.get(`${base}/newsletter/sitemap.xml`)).text();assert.ok(sitemap.includes('preview-approve'));assert.ok(!sitemap.includes('preview-reject'));
 await page.setViewportSize({width:1440,height:1100});await page.goto(`${base}/newsletter`);
 await page.screenshot({path:'/private/tmp/grayyachts-newsletter-checks/published-archive.png',fullPage:true});
 await page.goto(`${base}/newsletter/preview-approve`);await page.screenshot({path:'/private/tmp/grayyachts-newsletter-checks/article.png',fullPage:true});
 assert.equal(await page.locator('script[type="application/ld+json"]').count(),1);
 console.log('PASS: desktop/mobile layout, draft privacy, token rejection, GET read-only, approve, replay protection, reject, sitemap, and Article schema.');
} finally {await browser.close();}
