/* eslint-disable @next/next/no-img-element -- Existing brand asset. */
import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
import {newsletterEnv} from '@/lib/newsletter/db';
import {validToken,type Issue,type Article} from '@/lib/newsletter/core';
import NewsletterArticle from '@/components/marketing/newsletter-article';
export const dynamic='force-dynamic';
export const metadata:Metadata={title:'Private newsletter review | Gray Yachts',robots:{index:false,follow:false},referrer:'no-referrer'};
export default async function ReviewPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{token?:string}>}) {
 const {id}=await params;const {token=''}=await searchParams;const env=await newsletterEnv();
 const issue=await env.NEWSLETTER_DB.prepare('SELECT * FROM newsletter_issues WHERE id=?').bind(id).first<Issue>();
 if(!issue?.content||!await validToken(id,token,env.NEWSLETTER_AUTOMATION_SECRET,issue.review_revision))notFound();
 const article=JSON.parse(issue.content) as Article;
 const sources=JSON.parse(issue.sources) as {title:string;url:string}[];
 return <main className="min-h-screen bg-[#f7f4ee] text-slate-900"><div className="bg-[#060a12] px-6 py-10 text-white"><div className="mx-auto max-w-3xl"><img src="/brand/logo-nav.png" alt="Gray Yachts" width="100" height="100" className="mb-7"/><p className="text-xs uppercase tracking-[0.2em] text-[#c9a96e]">The Gray Yachts Journal · private editorial review</p><h1 className="mt-5 font-[family-name:var(--font-cormorant)] text-4xl md:text-5xl">{issue.title}</h1><p className="mt-5 text-slate-300">{issue.audience==='seller'?'Seller':'Buyer'} edition · Humanizer edited · {issue.status==='pending'?'Awaiting your decision':issue.status}</p></div></div><div className="mx-auto max-w-3xl px-6 py-12">
 {issue.status==='pending'?<form action={`/api/newsletter/review/${id}`} method="post" className="mb-14 border border-slate-300 bg-white p-6"><input type="hidden" name="token" value={token}/><h2 className="text-xl font-medium">Review before publishing</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">Check the advice and business claims below. Approve publishes this exact draft on GrayYachts.com. Reject keeps it private and saves your feedback for future drafts. Neither action sends an email to subscribers.</p><label htmlFor="feedback" className="mt-5 block text-sm font-medium">Notes for the next draft (optional)</label><textarea id="feedback" name="feedback" maxLength={3000} rows={3} className="mt-2 w-full border border-slate-300 p-3 text-base"/><div className="mt-5 flex flex-wrap gap-3"><button name="decision" value="approve" className="bg-[#162636] px-6 py-3 text-white">Approve & publish</button><button name="decision" value="reject" className="border border-slate-400 px-6 py-3">Reject draft</button></div></form>:<p className="mb-10 border border-slate-300 p-5">This draft has already been {issue.status}. {issue.status==='published'&&<a className="underline" href={`/newsletter/${issue.slug}`}>Read the published edition.</a>}</p>}
 <NewsletterArticle article={article} images={JSON.parse(issue.images)}/><div className="mt-12 border-t border-slate-300 pt-6"><h2 className="font-medium">Source notes</h2><p className="mt-2 text-sm text-slate-600">The editor checked this draft against the brokerage brief and the resources below. Please review the advice and supporting sources before approving.</p><ul className="mt-4 space-y-2 text-sm">{sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer" className="underline">{source.title}</a></li>)}</ul></div></div></main>;
}
